/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#pragma once
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <stdio.h>

#define STRING_END '\0'
#define NEW_LINE 0x5c

using namespace std;

const char PATH_TXT[] = "Paths.txt";
vector<string> paths;
unsigned int nr = 0;

void parseFile();
void start();

int main()
{
    cout << "Overwrite-Files started" << endl;
    start();
    cout << "Overwrite-Files ende" << endl;
    return 0;
}

class Operations
{
public:
    string path;
    string name;
    string folder;
    int var_k;

    virtual void calc(int k) = 0;
    virtual void printVars() = 0;
    virtual void overwrite() = 0;
    virtual void renaimFile() = 0;
    virtual void deleteFile() = 0;
};

class Test : public Operations
{
public:
    void calc(int k) override
    {
        ifstream file(paths[k]);
        if (!file.good())// exists
        {
            cout << path << " do not exists" << endl;
            exit(1);
        }
        if (!((folder + "/" + name) == path)) 
        {
            cout << path << " is not " << (folder + "/" + name) << endl;
        }
    }

    void printVars() override
    {}

    void overwrite() override
    {
        ifstream file(path, ios::binary);
        if (file.good()) {
            file.seekg(0, ios::end);
            std::streampos fileSize = file.tellg();
            file.seekg(0, ios::beg);
            char* buffer = new char[fileSize];
            file.read(buffer, fileSize);
            while (*buffer != STRING_END) {
                if (*buffer != 0x0) {
                    cout << path << " fehlerhalft überschrieben " << endl;
                    exit(1);
                }
                ++buffer;
            }
            delete[] buffer;
        } else {
            std::cout << "Failed to open file " << path << std::endl;
        }
    }

    void renaimFile() override
    {}

    void deleteFile() override
    {
        ifstream file(path, ios::binary);
        if (file.good()) {
            cout << path << " wurde nicht gelöscht " << endl;
        }
    }
};

class File : public Operations
{
private:
    int getFileLength() 
    {
        ifstream in_file(path, ios::binary);
        in_file.seekg(0, std::ios::end);
        int file_size = in_file.tellg();
        return file_size;
    }

public:
    void calc(int k) override
    {
        path = paths[k];
        var_k = k;
        int lastSlash = -1;
        for (int i = path.size() - 1; i >= 0; --i) {
            if (path[i] == 0x2F || path[i] == 0x5C) {
                lastSlash = i;
                break;
            }
        }
        name = path.substr(lastSlash + 1, string::npos);
        folder = path.substr(0, lastSlash);
    }

    void overwrite() override
    {
        fstream file(path, ios::in | ios::out);
        if (file.is_open()) {
            cout << "Die Datei wurde geöffnet." << endl;
        }
        else {
            cout << "Die Datei wurde nicht geöffnet." << endl;
        }
        file.seekp(0);
        int size = getFileLength();
        for (int i = 0; i < size; ++i) {
            file.put(0x0);
        }
        file.close();
    }

    void renaimFile() override
    {
        string newName = folder + "/" + to_string(var_k);
        int result = rename(path.c_str(), newName.c_str());
        if (result == 0) {
            cout << "File was renamed successfully." << endl;
        } else {
            cout << "Error renaming file." << endl;
        }
    }

    void printVars() override
    {
        cout << path << endl;
        cout << name << endl;
        cout << folder << endl;
        cout << endl << endl;
    }

    void deleteFile() override
    {
        
    }
};

template <typename T>
class Stack : Operations {
public:
    void calc(int k) override
    {
        T::calc(k);
    }

    void printVars() override
    {
        T::printVars();
    }

    void overwrite() override
    {
        T::overwrite();
    }

    void renaimFile() override
    {
        T::renaimFile();
    }

    void deleteFile() override
    {
        T::deleteFile();
    }
};

template <typename T>
void execute(T f)
{
    for (int i = 0; i < nr; ++i) {
        f.calc(i);
        f.printVars();
        f.overwrite();
        f.renaimFile();
        f.deleteFile();
    }
}

void start()
{
    parseFile();
    execute<File>(new File());
    execute<Test>(new Test());
}

void parseFile()
{
    fstream pathFile;
    pathFile.open(PATH_TXT, std::ios::in);
    if (pathFile.is_open()) {
        string buffer;
        while (getline(pathFile, buffer)) {
            paths.push_back(buffer);
            ++nr;
        }
        pathFile.close();
    }
    else {
        cout << "ERROR: " << PATH_TXT << " is not open.";
        exit(1);
    }
}